"""init

Revision ID: 1a5e81ee8528
Revises: 
Create Date: 2022-03-12 00:15:50.394159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5e81ee8528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'account_id')
    # ### end Alembic commands ###
