"""empty message

Revision ID: 599ce956d1af
Revises: 8ef841bde923
Create Date: 2023-03-23 22:59:06.347671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "599ce956d1af"
down_revision = "8ef841bde923"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "two_factor_auth_type",
            sa.String(length=50),
            server_default="2fa_otp_email",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "two_factor_auth_type")
    # ### end Alembic commands ###
