"""empty message

Revision ID: 8ef841bde923
Revises: 34db1211aca5
Create Date: 2023-03-12 23:12:03.393615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ef841bde923"
down_revision = "34db1211aca5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_is_confirmed", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "users", sa.Column("email_confirmed_on", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_confirmed_on")
    op.drop_column("users", "email_is_confirmed")
    # ### end Alembic commands ###
