"""removed invoice_mode and next_invoice_no from organization model/routes

Revision ID: da69983e2793
Revises: 1a5e81ee8528
Create Date: 2022-03-13 21:28:51.661425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da69983e2793'
down_revision = '1a5e81ee8528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'next_invoice_no')
    op.drop_column('organizations', 'invoice_no_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('invoice_no_mode', mysql.VARCHAR(length=10), server_default=sa.text("'manual'"), nullable=False))
    op.add_column('organizations', sa.Column('next_invoice_no', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
