"""empty message
Revision ID: ebd75be7d7ec
Revises: 599ce956d1af
Create Date: 2023-06-25 22:59:28.038873
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebd75be7d7ec'
down_revision = '599ce956d1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    contacts_seq = sa.Sequence('contacts_id_seq')
    op.execute(sa.schema.CreateSequence(contacts_seq))
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), contacts_seq, server_default=contacts_seq.next_value(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registration_no', sa.String(length=50), server_default='', nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('contactperson_name', sa.String(length=255), nullable=True),
    sa.Column('contactperson_email', sa.String(length=255), nullable=True),
    sa.Column('is_company', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('type', sa.String(length=10), server_default='client', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'name', 'registration_no'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('invoices_client_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])
        batch_op.drop_column('client_id')

    op.drop_table('clients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoices_client_id_fkey', 'clients', ['client_id'], ['id'])
        batch_op.drop_column('contact_id')

    op.create_table('clients',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('clients_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('registration_no', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contactperson_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contactperson_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), server_default=sa.text("'company'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='clients_country_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='clients_organization_id_fkey'),
    sa.PrimaryKeyConstraint('organization_id', 'name', 'registration_no', name='clients_pkey'),
    sa.UniqueConstraint('id', name='clients_id_key')
    )
    op.drop_table('contacts')
    # ### end Alembic commands ###
